[platformio]
default_envs = esp32dev

[env]
platform = espressif32@7.1.3
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = beegee-tokyo/DHT sensor library for ESPx@1.19.0

[env:esp32dev]

[env:wokwi]
build_flags = -DWOKWI_DHT22
